import { query, mutation } from "./_generated/server"
import { v } from "convex/values"
import { currentOwner, requireOwner } from "./authz"

export const overview=query({
 args:{},returns:v.object({total:v.number(),hot:v.number(),high:v.number(),imports:v.number(),contactable:v.number(),confirmed:v.number(),sourcing:v.number(),quotes:v.number(),won:v.number()}),
 handler:async(ctx)=>{
  if(!(await currentOwner(ctx))) return {total:0,hot:0,high:0,imports:0,contactable:0,confirmed:0,sourcing:0,quotes:0,won:0}
  const leads=await ctx.db.query("leads").collect()
  return {total:leads.length,hot:leads.filter(x=>x.intentStrength>=90).length,high:leads.filter(x=>x.intentStrength>=70&&x.intentStrength<90).length,imports:leads.filter(x=>x.importRequired).length,contactable:leads.filter(x=>Boolean(x.publicContact)).length,confirmed:leads.filter(x=>x.leadStatus==="requirement_confirmed").length,sourcing:leads.filter(x=>x.leadStatus==="sourcing").length,quotes:leads.filter(x=>x.leadStatus==="quote_sent"||x.leadStatus==="negotiation").length,won:leads.filter(x=>x.leadStatus==="won").length}
 }
})
export const pipeline=query({args:{},returns:v.array(v.object({status:v.string(),count:v.number()})),handler:async(ctx)=>{if(!(await currentOwner(ctx)))return[];const statuses=["new","qualified","contacted","responded","requirement_confirmed","sourcing","quote_sent","negotiation","won","lost"];const leads=await ctx.db.query("leads").collect();return statuses.map(status=>({status,count:leads.filter(x=>x.leadStatus===status).length}))}})
export const sourcePerformance=query({args:{},returns:v.array(v.object({source:v.string(),signals:v.number(),hot:v.number(),imports:v.number(),contactable:v.number()})),handler:async(ctx)=>{if(!(await currentOwner(ctx)))return[];const leads=await ctx.db.query("leads").collect();const map=new Map<string,{signals:number,hot:number,imports:number,contactable:number}>();for(const l of leads){const x=map.get(l.source)||{signals:0,hot:0,imports:0,contactable:0};x.signals++;if(l.intentStrength>=90)x.hot++;if(l.importRequired)x.imports++;if(l.publicContact)x.contactable++;map.set(l.source,x)}return [...map.entries()].map(([source,x])=>({source,...x})).sort((a,b)=>b.signals-a.signals)}})
export const upsertSource=mutation({args:{name:v.string(),kind:v.string(),enabled:v.boolean(),queryTemplates:v.array(v.string()),notes:v.optional(v.string())},returns:v.id("sources"),handler:async(ctx,args)=>{await requireOwner(ctx);const existing=await ctx.db.query("sources").collect();const hit=existing.find(x=>x.name===args.name);const now=Date.now();if(hit){await ctx.db.patch(hit._id,{...args,lastSearched:hit.lastSearched,resultCount:hit.resultCount,qualifiedCount:hit.qualifiedCount,status:hit.status});return hit._id}return ctx.db.insert("sources",{...args,status:"ready",lastSearched:now,resultCount:0,qualifiedCount:0})}})
export const sources=query({args:{},returns:v.array(v.object({_id:v.id("sources"),_creationTime:v.number(),name:v.string(),kind:v.string(),enabled:v.boolean(),queryTemplates:v.array(v.string()),status:v.string(),lastRun:v.optional(v.number()),lastSearched:v.number(),resultCount:v.number(),qualifiedCount:v.number(),notes:v.optional(v.string())})),handler:async(ctx)=>{if(!(await currentOwner(ctx)))return[];return ctx.db.query("sources").order("desc").collect()}})
export const runs=query({args:{},returns:v.array(v.object({_id:v.id("discoveryRuns"),_creationTime:v.number(),startedAt:v.number(),completedAt:v.optional(v.number()),queryCount:v.number(),candidates:v.number(),created:v.number(),updated:v.number(),status:v.string(),error:v.optional(v.string())})),handler:async(ctx)=>{if(!(await currentOwner(ctx)))return[];return ctx.db.query("discoveryRuns").withIndex("by_started").order("desc").take(10)}})
